services:
  ### ==========================================
  ### 1. APLICACIÓN PRINCIPAL
  ### ==========================================
  open_balena_apis:
    build:
      context: ./backend # Coincide con tu carpeta 'backend'
      dockerfile: Dockerfile # Busca el archivo renombrado
    container_name: open_balena_apis
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env # Variables internas de Python
    volumes:
      - ./backend:/app
    networks:
      InspecNet:
        ipv4_address: 172.16.0.2
    depends_on:
      - redis
      - postgres_principal

  frontend:
    build:
      context: ./frontend # Coincide con tu carpeta 'frontend'
      dockerfile: Dockerfile
    container_name: frontend_inspector
    restart: unless-stopped
    ports:
      - "3001:80" # Frontend expone 80 internamente (Nginx), 3001 fuera
    depends_on:
      - redis
      - postgres_principal
    networks:
      InspecNet:
        ipv4_address: 172.16.0.4

  ### ==========================================
  ### 2. BASE DE DATOS Y CACHÉ
  ### ==========================================
  redis:
    image: redis:latest
    container_name: redis_inspector
    restart: unless-stopped
    # Redis usa variables del .env RAÍZ directamente
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    networks:
      InspecNet:
        ipv4_address: 172.16.0.6
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  postgres_principal:
    build:
      context: ./database # Coincide con tu carpeta 'database'
      dockerfile: Dockerfile
    container_name: postgres_inspector
    # Usamos variables del .env RAÍZ para la infraestructura
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Nota: En tu Dockerfile ya copiaste los scripts, 
      # pero dejarlos aquí no hace daño para desarrollo local
      - ./database/init.sql:/docker-entrypoint-initdb.d/01_init.sql
    restart: unless-stopped
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      InspecNet:
        ipv4_address: 172.16.0.8
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ### ==========================================
  ### 3. SEGURIDAD
  ### ==========================================
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak_inspector
    restart: unless-stopped
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://172.16.0.8:5432/keycloak_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      # quitar despues
      - ./keycloak_config:/opt/keycloak/data/import
    depends_on:
      postgres_principal:
        condition: service_healthy
    networks:
      InspecNet:
        ipv4_address: 172.16.0.10

  krakend:
    build:
      context: ./gateway # Coincide con tu carpeta 'gateway'
      dockerfile: Dockerfile
    container_name: krakend_inspector
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./gateway/krakend.json:/etc/krakend/krakend.json
    depends_on:
      - keycloak
      - open_balena_apis
    networks:
      InspecNet:
        ipv4_address: 172.16.0.11

  ### ==========================================
  ### 4. VPN
  ### ==========================================
  wg-easy:
    image: weejewel/wg-easy:latest
    container_name: wg-easy_inspector
    restart: always
    ports:
      - "${WG_PORT:-51820}:51820/udp"
      - "${WG_EASY_PORT:-51821}:51821/tcp"
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD=${WG_EASY_PASSWORD}
      - WG_PORT=${WG_PORT:-51820}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_ADDRESS_RANGE_SIZE=${WG_DEFAULT_ADDRESS_RANGE_SIZE:-24}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - WG_MTU=${MTU:-1420}
      - TZ=${TZ:-America/Bogota}
      - WG_PERSISTENT_KEEPALIVE=25
      - MAX_CLIENTS=${WG_MAX_CLIENTS:-100}
    volumes:
      - ./wireguard_data/etc:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      InspecNet:
        ipv4_address: 172.16.0.12

  wg-fastapi:
    build:
      context: ./vpn # Coincide con tu carpeta 'vpn'
      dockerfile: Dockerfile
    container_name: wg-fastapi_inspector
    restart: always
    expose:
      - "5000"
    volumes:
      - ./wireguard_data/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./vpn/.env # Usa su propio archivo .env
    depends_on:
      - wg-easy
    networks:
      InspecNet:
        ipv4_address: 172.16.0.13

networks:
  InspecNet:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/28

volumes:
  redis_data:
    driver: local
  pgdata:
    driver: local
