FROM krakend:latest

USER root

# Install ca-certificates
RUN apk update && apk add --no-cache ca-certificates

# Copy and install our Root CA
COPY rootCA.crt /usr/local/share/ca-certificates/rootCA.crt
RUN update-ca-certificates

# Copy config
COPY krakend.json /etc/krakend/krakend.json

USER krakend