FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    ca-certificates \
    lsb-release \
    gcc \
    g++ \
    make \
    libpq-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get update \
    && apt-get install -y nodejs \
    && node -v \
    && npm -v

COPY ca.pem /usr/local/share/ca-certificates/openbalena-ca.crt
RUN update-ca-certificates

ENV CERTS_PATH="/usr/local/share/ca-certificates/openbalena-ca.crt" \
    NODE_EXTRA_CA_CERTS="/usr/local/share/ca-certificates/openbalena-ca.crt"

RUN echo "balenaUrl: 'inspectordm.tigo.com.co'" > /root/.balenarc.yml

RUN npm install -g balena-cli@22.2.4 --unsafe-perm
RUN balena version

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
