"""add passive_deletes to registro-historial relationship

Revision ID: 3828f9b6467c
Revises: 968777bf7791
Create Date: 2025-07-15 15:55:20.299225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3828f9b6467c'
down_revision: Union[str, Sequence[str], None] = '968777bf7791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
