"""add uuid to registros

Revision ID: 4b61175457e7
Revises: b0bf7df9c8da
Create Date: 2025-07-22 11:44:45.074464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b61175457e7'
down_revision: Union[str, Sequence[str], None] = 'b0bf7df9c8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros', sa.Column('uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros', 'uuid')
    # ### end Alembic commands ###
