"""add_unique_constraints_to_registros

Revision ID: 5e358f79d755
Revises: d9ca4c7bbd7a
Create Date: 2025-07-03 16:46:53.236406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e358f79d755'
down_revision: Union[str, Sequence[str], None] = 'd9ca4c7bbd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_nombre_unique', 'registros', ['nombre'], unique=True)
    op.create_index('idx_numero_inspector_unique', 'registros', ['numero_inspector'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_numero_inspector_unique', table_name='registros')
    op.drop_index('idx_nombre_unique', table_name='registros')
    # ### end Alembic commands ###
