"""add cascade delete to historial_cambios.registro_id

Revision ID: 968777bf7791
Revises: d2d82f1c9c13
Create Date: 2025-07-15 15:18:00.607411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968777bf7791'
down_revision: Union[str, Sequence[str], None] = 'd2d82f1c9c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('historial_cambios_registro_id_fkey'), 'historial_cambios', type_='foreignkey')
    op.create_foreign_key(None, 'historial_cambios', 'registros', ['registro_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historial_cambios', type_='foreignkey')
    op.create_foreign_key(op.f('historial_cambios_registro_id_fkey'), 'historial_cambios', 'registros', ['registro_id'], ['id'])
    # ### end Alembic commands ###
