"""add activo field to usuarios table

Revision ID: ac467c874381
Revises: 3828f9b6467c
Create Date: 2025-07-16 17:05:18.866804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac467c874381'
down_revision: Union[str, Sequence[str], None] = '3828f9b6467c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), nullable=True))
    op.execute('UPDATE usuarios SET activo = TRUE')
    op.alter_column('usuarios', 'activo', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'activo')
    # ### end Alembic commands ###
