"""add historial_usuarios table

Revision ID: b0bf7df9c8da
Revises: ac467c874381
Create Date: 2025-07-16 17:18:25.388964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bf7df9c8da'
down_revision: Union[str, Sequence[str], None] = 'ac467c874381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('admin_que_realizo_cambio', sa.String(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('campo', sa.String(), nullable=True),
    sa.Column('valor_anterior', sa.String(), nullable=True),
    sa.Column('valor_nuevo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_usuarios_fecha'), 'historial_usuarios', ['fecha'], unique=False)
    op.create_index(op.f('ix_historial_usuarios_id'), 'historial_usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_historial_usuarios_usuario_id'), 'historial_usuarios', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_usuarios_usuario_id'), table_name='historial_usuarios')
    op.drop_index(op.f('ix_historial_usuarios_id'), table_name='historial_usuarios')
    op.drop_index(op.f('ix_historial_usuarios_fecha'), table_name='historial_usuarios')
    op.drop_table('historial_usuarios')
    # ### end Alembic commands ###
