"""add historial_cambios table

Revision ID: d2d82f1c9c13
Revises: 5e358f79d755
Create Date: 2025-07-15 15:08:36.571454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d82f1c9c13'
down_revision: Union[str, Sequence[str], None] = '5e358f79d755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_cambios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('numero_inspector', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('campo', sa.String(), nullable=True),
    sa.Column('valor_anterior', sa.String(), nullable=True),
    sa.Column('valor_nuevo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['registro_id'], ['registros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_cambios_fecha'), 'historial_cambios', ['fecha'], unique=False)
    op.create_index(op.f('ix_historial_cambios_id'), 'historial_cambios', ['id'], unique=False)
    op.create_index(op.f('ix_historial_cambios_numero_inspector'), 'historial_cambios', ['numero_inspector'], unique=False)
    op.create_index(op.f('ix_historial_cambios_registro_id'), 'historial_cambios', ['registro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_cambios_registro_id'), table_name='historial_cambios')
    op.drop_index(op.f('ix_historial_cambios_numero_inspector'), table_name='historial_cambios')
    op.drop_index(op.f('ix_historial_cambios_id'), table_name='historial_cambios')
    op.drop_index(op.f('ix_historial_cambios_fecha'), table_name='historial_cambios')
    op.drop_table('historial_cambios')
    # ### end Alembic commands ###
