# database/Dockerfile
FROM postgres:17

# Configuración de Zona Horaria
ENV TZ=America/Bogota
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Instalación de extensiones (PostGIS, Partman, Cron)
RUN apt-get update && apt-get install -y \
    postgresql-17-partman \
    postgresql-contrib \
    postgis \
    postgresql-17-postgis-3 \
    postgresql-17-cron \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copia de configuraciones y scripts
COPY postgresql.conf /etc/postgresql/postgresql.conf
COPY pg_hba.conf /etc/postgresql/pg_hba.conf
COPY init.sql /docker-entrypoint-initdb.d/01_init.sql
COPY defaults_registers.sql /docker-entrypoint-initdb.d/02_defaults_registers.sql

# Permisos
RUN chmod 755 /docker-entrypoint-initdb.d/*.sql && \
    chown postgres:postgres /etc/postgresql/postgresql.conf /etc/postgresql/pg_hba.conf

EXPOSE 5432
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]