# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Permitir acceso local (dentro del contenedor)
local   all             all                                     trust

# Permitir acceso desde CUALQUIER IP (0.0.0.0/0) usando contraseña encriptada
# Esto cubre la red interna de Docker (172.x.x.x) y tu acceso local
host    all             all             0.0.0.0/0               scram-sha-256